config/routes.rb
Infodisplay::Application.routes.draw do

  resources :infomessages do
  end

  root 'infomessages#index'

end

app/models/infomessage.rb
class Infomessage < ActiveRecord::Base
  mount_uploader :image, InfoimageUploader

  before_save :set_priority

  default_scope { order(:priority) }

private
  def set_priority
    if self.priority == nil
      if Infomessage.count > 0
        self.priority = Infomessage.first.priority - 1
      else
        self.priority = 0
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infomessages_controller.rb
class InfomessagesController < ApplicationController
  before_filter :load_message
  respond_to :json, :html, only: :index
  respond_to :json

  def index
    @messages = Infomessage.all
    respond_with @messages
  end

  def show
    respond_with @message
  end

  def edit
    respond_with @message
  end

  def new
    @message = Infomessage.new
    respond_with @message
  end

  def create
    @message = Infomessage.new()
    @message.update_attributes!(edit_params)
    saved = @message.save
    if saved
      respond_with @message
    else
      respond_with @message.errors
    end
  end

  def update
    @message.update_attributes!(edit_params)
    saved = @message.save
    if saved
      respond_with @message
    else
      respond_with @message.errors
    end
  end

  def destroy
    @message.destroy
    respond_with status: :ok
  end

private
  def load_message
    @message = Infomessage.where(id: params[:id].to_i).first if params.has_key? :id
  end

  def edit_params
    params.require(:infomessage).permit(:text, :image, :priority, :display_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infomessages_helper.rb
module InfomessagesHelper
end

app/views/infomessages/edit.html.erb
<% if @message.new_record? %>
  <h2>Create Message</h2>
<% else %>
  <h2>Edit Message</h2>
<% end %>
<%= form_for(@message) do |f| %>
  <div class="form-group">
    <%= f.label :text, "Message Text" %>
    <%= f.text_area :text, class: "input-xlarge" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image %><br/>
  </div>
  <%= f.submit 'Save', class: "btn" %>
<% end %>

app/views/infomessages/index.html.erb
<table class="table table-striped" id="info_messages_list">
<tr><th>Priority</th><th>Text</th><th>Image</th><th>Action</th></tr>
<% @messages.each do |message| %>
<tr id="info_message<%= message.id%>">
  <td><%= message.priority %></td>
  <td><%= message.text %></td>
  <td></td>
  <td>
    <%= link_to "Show", message, class: "btn show-message", id: message.id %>
    <%= link_to "Edit", edit_infomessage_path(message), class: "btn edit-message", id: message.id %>
    <%= link_to "Delete", message, class: "btn delete-message btn-danger", id: message.id, method: :delete, confirm: 'Are you sure?' %>
</tr>
<% end %>
</table>

<%= link_to raw("<span class='btn new_message'>New Message</span>"), new_infomessage_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Infodisplay" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>